export const courses = [
    {
        title: "PRINCE2® 7 Practitioner",
        description: "Interactive & Gamified Learning",
        createdAt: "2024-01-05",
        imagePath: "/images/PM4.png",
        author: "Author Name",
        slug: "/course/prince2-practitioner",
        modulesCount: 22,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£199.99",
        originalPrice: "£1455",
        discountedPrice: "£1099",
    },
    {
        title: "Data Science Bootcamp",
        description: "Master Data Science with Python",
        createdAt: "2024-01-10",
        imagePath: "/images/PM2.png",
        author: "Author Name",
        slug: "/course/data-science-bootcamp",
        modulesCount: 30,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£249.99",
        originalPrice: "£1999",
        discountedPrice: "£1699",
    },
    {
        title: "PRINCE2® 7 Practitioner",
        description: "Interactive & Gamified Learning",
        createdAt: "2024-01-01",
        imagePath: "/images/PM3.png",
        author: "Author Name",
        slug: "/course/prince2-practitioner",
        modulesCount: 22,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£199.99",
        originalPrice: "£1455",
        discountedPrice: "£1099",
    },
    {
        title: "Data Science Bootcamp",
        description: "Master Data Science with Python",
        createdAt: "2024-01-10",
        imagePath: "/images/PM4.png",
        author: "Author Name",
        slug: "/course/data-science-bootcamp",
        modulesCount: 30,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£249.99",
        originalPrice: "£1999",
        discountedPrice: "£1699",
    },
    {
        title: "Data Science Bootcamp",
        description: "Master Data Science with Python",
        createdAt: "2024-01-10",
        imagePath: "/images/PM6.png",
        author: "Author Name",
        slug: "/course/data-science-bootcamp",
        modulesCount: 30,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£249.99",
        originalPrice: "£1999",
        discountedPrice: "£1699",
    },
    {
        title: "PRINCE2® 7 Practitioner",
        description: "Interactive & Gamified Learning",
        createdAt: "2024-01-01",
        imagePath: "/images/PM2.png",
        author: "Author Name",
        slug: "/course/prince2-practitioner",
        modulesCount: 22,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£199.99",
        originalPrice: "£1455",
        discountedPrice: "£1099",
    }

]