export const courses = [
    {
        title: "PRINCE2® 7 Practitioner",
        description: "The PRINCE2® 7 Practitioner Interactive & Gamified Learning is designed for aspiring and current proj...",
        createdAt: "2024-01-05",
        imagePath: "/images/PM4.png",
        author: "Author Name",
        slug: "/course/prince2-practitioner",
        modulesCount: 22,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£199.99",
        originalPrice: "£1455",
        discountedPrice: "£1099",
    },
    {
        title: "Data Science Bootcamp",
        description: "PRINCE2® 7 Foundation Gamified Certification comprises innovative additions and improvements. T..",
        createdAt: "2024-01-10",
        imagePath: "/images/PM2.png",
        author: "Author Name",
        slug: "/course/data-science-bootcamp",
        modulesCount: 30,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£249.99",
        originalPrice: "£1999",
        discountedPrice: "£1699",
    },
    {
        title: "PRINCE2® 7 Practitioner",
        description: "The PRINCE2® 7 Practitioner Interactive & Gamified Learning is designed for aspiring and current proje...",
        createdAt: "2024-01-01",
        imagePath: "/images/PM3.png",
        author: "Author Name",
        slug: "/course/prince2-practitioner",
        modulesCount: 22,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£199.99",
        originalPrice: "£1455",
        discountedPrice: "£1099",
    },
    {
        title: "Data Science Bootcamp",
        description: "Do you wish to qualify as a Lean Six Sigma Practitioner? Upon completing the Yellow and Green Belts, individu... ",
        createdAt: "2024-01-10",
        imagePath: "/images/PM4.png",
        author: "Author Name",
        slug: "/course/data-science-bootcamp",
        modulesCount: 30,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£249.99",
        originalPrice: "£1999",
        discountedPrice: "£1699",
    },
    {
        title: "Data Science Bootcamp",
        description: "The PRINCE2® 7 Practitioner Gamified Certification is designed for project managers and project  profession...",
        createdAt: "2024-01-10",
        imagePath: "/images/PM6.png",
        author: "Author Name",
        slug: "/course/data-science-bootcamp",
        modulesCount: 30,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£249.99",
        originalPrice: "£1999",
        discountedPrice: "£1699",
    },
    {
        title: "PRINCE2® 7 Practitioner",
        description: "PRINCE2® 7 Foundation Gamified Certification comprises innovative additions and improvements. T..",
        createdAt: "2024-01-01",
        imagePath: "/images/PM2.png",
        author: "Author Name",
        slug: "/course/prince2-practitioner",
        modulesCount: 22,
        certificate: "Professional Certificate",
        discountPercentage: 0,
        pricePerMonth: "£199.99",
        originalPrice: "£1455",
        discountedPrice: "£1099",
    }

]